# Generated by Django 4.1.1 on 2022-10-11 07:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_pic',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
